version: '3'
services:
  web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000 npm run dev
 
      ports:
            - "8501:8888"
      working_dir: /usr/src/service
      context: .
      args:
    - buildno=1
    - gitcommithash=cdc3b19
 

        
 
